### ISSUE TITLE
Wait strategy does not work when restarting

### ISSUE THREAD

**Issue by SgtSilvio** [hivemq/hivemq-testcontainer#66]
## Expected behavior
The wait strategy should always work, also when restarting a container

## Actual behavior
When restarting a container, the wait strategy does not work, returns too early, almost instant

Problem is the use of MultiLogMessageWaitStrategy, which holds the result of the first start.

### Steps
1. start => wait strategy works
2. stop
3. start => wait strategy does not work, returns too early, almost instant

## Details
- Affected HiveMQ Testcontainer version(s): 1.3.0
- Used JVM version:

**Comment by YannickWeber** [comment]
resolved by #67
